

!IF "$(PLATFORM)"=="X64"
TargetPlatform=x64
!ELSE
TargetPlatform=x86
!ENDIF

BinDir=bin\$(TargetPlatform)
WtraceBins=bin\$(TargetPlatform)\wtrace.exe

CppSources=..\..\src\Main.cpp  \
		..\..\src\debugger.cpp  \
		..\..\src\Output.cpp  \
		..\..\src\Utils.cpp  \

all: clean $(WtraceBins)
	echo done!

$(WtraceBins): src\debugger.cpp
	IF NOT EXIST $(BinDir) mkdir $(BinDir)
	cd $(BinDir)
	cl /Zi \
		/EHsc \
		$(CppSources) \
		/Fewtrace \
		/I"C:\Program Files (x86)\Windows Kits\8.1\Include\um" \
		/DEBUG  \
		/W4  \
		/RTCs \
		"ntdll.lib" \
		"Dbghelp.lib"
	cd ..\..

publish: latest\$(TargetPlatform) $(BinDir)\wtrace.exe $(BinDir)\wtrace.pdb $(BinDir)\vc120.pdb
	copy $(BinDir)\*.exe latest\$(TargetPlatform)
	copy $(BinDir)\*.pdb latest\$(TargetPlatform)
	echo Built by : > latest\$(TargetPlatform)\readme.txt
	whoami >> latest\$(TargetPlatform)\readme.txt
	time /t >> latest\$(TargetPlatform)\readme.txt
	date /t >> latest\$(TargetPlatform)\readme.txt

clean:
	IF EXIST bin\$(TargetPlatform) del /q bin\$(TargetPlatform)\*

