
all: clean bin build_test 
	echo done!

bin: src\debugger.cpp
	IF NOT EXIST bin mkdir bin
	cd bin
	cl /Zi \
	/EHsc \
	..\src\debugger.cpp  \
	/FeDebugger \
	/I"C:\Program Files (x86)\Windows Kits\8.1\Include\um" \
	/DEBUG  \
	"C:\Program Files (x86)\Windows Kits\8.1\Lib\winv6.3\um\x64\ntdll.lib"
	cd ..

build_test: src\debugme.cpp
	IF NOT EXIST test mkdir test
	cd test
	cl /Zi ..\src\debugme.cpp /FeDebugMe
	cd ..


clean:
	IF EXIST bin del bin /s/q bin\* && rd bin
	IF EXIST test del test /s/q test\* && rd test

