

!IF "$(PLATFORM)"=="ARM"
TargetPlatform=ARM
!ELSE
!IF "$(PLATFORM)"=="X64"
TargetPlatform=x64
!ELSE
TargetPlatform=x86
!ENDIF
!ENDIF

BinDir=bin\$(TargetPlatform)
WtraceBins=bin\$(TargetPlatform)\wtrace.exe

CppSources=..\..\src\Main.cpp  \
		..\..\src\debugger.cpp \
		..\..\src\wow64.cpp    \
		..\..\src\Output.cpp   \
		..\..\src\Utils.cpp    \
		..\..\src\plugins\html.cpp    \
		..\..\src\plugins\interactive.cpp    \
		..\..\src\plugins\Tracer.cpp    \

HeaderFiles=..\..\src\inc\

PluginHeaderFiles=..\..\src\plugins\

all: clean $(WtraceBins)
	echo done!

$(WtraceBins): src\debugger.cpp src\wow64.cpp src\output.cpp src\plugins\html.cpp src\plugins\interactive.cpp  src\main.cpp src\plugins\tracer.cpp
	IF NOT EXIST $(BinDir) mkdir $(BinDir)
	cd $(BinDir)
	cl /Zi \
		/EHsc \
		$(CppSources) \
		/Fewtrace \
		/I"C:\Program Files (x86)\Windows Kits\8.1\Include\um" \
		/I"$(HeaderFiles)" \
		/I"$(PluginHeaderFiles)" \
		/DEBUG  \
		/W4  \
		/RTCs \
		"ntdll.lib" \
		"Dbghelp.lib"
	cd ..\..

clean:
	IF EXIST bin\$(TargetPlatform) del /q bin\$(TargetPlatform)\*

####################################################333
# PUBLISH A NEW VERSION TO LATEST
publish: latest\$(TargetPlatform) $(BinDir)\wtrace.exe $(BinDir)\wtrace.pdb $(BinDir)\vc120.pdb
	copy $(BinDir)\*.exe latest\$(TargetPlatform)
	copy $(BinDir)\*.pdb latest\$(TargetPlatform)
	echo Built by : > latest\$(TargetPlatform)\readme.txt
	whoami >> latest\$(TargetPlatform)\readme.txt
	time /t >> latest\$(TargetPlatform)\readme.txt
	date /t >> latest\$(TargetPlatform)\readme.txt

